sudo: false
language: python
python:
  - "2.7"
  - "3.6"
  - "nightly"

branches:
  except:
    - gh-pages
    - master
    - hotfix-issue-46
    
install:
# work-around to install cryptography dependency of known setup-tools bug
  - pip install -r requirements.txt
  - python setup.py -q build
  - python setup.py -q install
  - pip install tox-travis
  
# command to run tests
script: pytest

before_deploy:
- test $TRAVIS_TEST_RESULT = 0 \# check that build passed successfully
  && pip install -r requirements.txt \
  && python setup.py build \
  && python setup.py publish \
  && python setup.py install \
  && cd dist \
  && cd $TRAVIS_BUILD_DIR \
  && unzip webbreaker-$TRAVIS_BRANCH.zip dist

deploy:
  provider: releases
  api_key:
    secure: YOUR_API_KEY_ENCRYPTED
  file: file: webbreaker-$TRAVIS_BRANCH.zip
  skip_cleanup: true
  on:
    condition: $PRODBUILDCOMPLETE = true
    repo: target/webbreaker
    all_branches: true
    tags: true
  
